# Generated by Django 4.2.16 on 2025-07-23 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('short_description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('bullet_points', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('amazon_aplus_content', models.TextField(blank=True, help_text='Amazon A+ content suggestions')),
                ('amazon_backend_keywords', models.TextField(blank=True)),
                ('tiktok_video_script', models.TextField(blank=True)),
                ('tiktok_hashtags', models.TextField(blank=True)),
                ('tiktok_hooks', models.TextField(blank=True)),
                ('etsy_tags', models.TextField(blank=True)),
                ('etsy_materials', models.TextField(blank=True)),
                ('walmart_key_features', models.TextField(blank=True)),
                ('walmart_specifications', models.TextField(blank=True)),
                ('shopify_seo_title', models.TextField(blank=True)),
                ('shopify_meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_type', models.CharField(max_length=50)),
                ('suggestion', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('implemented', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.generatedlisting')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('competition', models.CharField(blank=True, max_length=20)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.generatedlisting')),
            ],
        ),
    ]
