# Generated by Django 4.2.16 on 2025-07-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_whats_in_box_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlisting',
            name='conversion_score',
            field=models.FloatField(blank=True, help_text='Conversion optimization score (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='emotion_score',
            field=models.FloatField(blank=True, help_text='Emotional engagement score (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='faqs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='guarantee',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='hero_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='hero_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Overall quality score (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='social_proof',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='trust_builders',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='trust_score',
            field=models.FloatField(blank=True, help_text='Trust and credibility score (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='whats_in_box',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image_type',
            field=models.CharField(choices=[('hero', 'Hero Shot'), ('infographic', 'Infographic'), ('lifestyle', 'Lifestyle'), ('testimonial', 'Testimonial')], max_length=20),
        ),
    ]
