# Generated by Django 4.2.16 on 2025-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_generatedlisting_conversion_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_assembly_required',
            field=models.BooleanField(default=False, help_text='Assembly required flag'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_attributes',
            field=models.TextField(blank=True, help_text='Category-specific attributes JSON'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_category_path',
            field=models.CharField(blank=True, help_text='Category hierarchy', max_length=500),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_compliance_certifications',
            field=models.TextField(blank=True, help_text='Safety/compliance certs'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_gtin_upc',
            field=models.CharField(blank=True, help_text='GTIN/UPC code', max_length=14),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_manufacturer_part',
            field=models.CharField(blank=True, help_text='Manufacturer part number', max_length=100),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_product_name',
            field=models.CharField(blank=True, help_text='Walmart product name (200 char limit)', max_length=200),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_product_type',
            field=models.CharField(blank=True, help_text='Product type/category', max_length=100),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_shelf_description',
            field=models.TextField(blank=True, help_text='Brief shelf description'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_shipping_dimensions',
            field=models.TextField(blank=True, help_text='L x W x H dimensions'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_shipping_weight',
            field=models.CharField(blank=True, help_text='Shipping weight with unit', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_short_description',
            field=models.TextField(blank=True, help_text='Rich HTML description (4000 chars)'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_sku_id',
            field=models.CharField(blank=True, help_text='SKU identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_swatch_images',
            field=models.TextField(blank=True, help_text='Swatch/variant images'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_video_urls',
            field=models.TextField(blank=True, help_text='Product video URLs'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_warranty_info',
            field=models.TextField(blank=True, help_text='Warranty details'),
        ),
        migrations.AlterField(
            model_name='generatedlisting',
            name='walmart_key_features',
            field=models.TextField(blank=True, help_text='Bullet points of key features'),
        ),
        migrations.AlterField(
            model_name='generatedlisting',
            name='walmart_specifications',
            field=models.TextField(blank=True, help_text='Technical specifications JSON'),
        ),
    ]
