# Generated by Django 4.2.16 on 2025-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_generatedlisting_walmart_assembly_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedlisting',
            name='walmart_product_name',
        ),
        migrations.RemoveField(
            model_name='generatedlisting',
            name='walmart_shelf_description',
        ),
        migrations.RemoveField(
            model_name='generatedlisting',
            name='walmart_short_description',
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_description',
            field=models.TextField(blank=True, help_text='Plain text narrative description (min 150 words)'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_product_title',
            field=models.CharField(blank=True, help_text='Walmart product title (100 char hard limit)', max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedlisting',
            name='walmart_key_features',
            field=models.TextField(blank=True, help_text='3-10 bullet points, max 80 chars each, plain text only'),
        ),
    ]
