# Generated by Django 5.1.3 on 2025-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_generatedlisting_walmart_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlisting',
            name='amazon_keywords',
            field=models.TextField(blank=True, help_text='Amazon frontend display keywords'),
        ),
    ]
