# Generated by Django 5.1.3 on 2025-08-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_generatedlisting_amazon_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_attributes',
            field=models.TextField(blank=True, help_text='Etsy-specific attributes (JSON)'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_care_instructions',
            field=models.TextField(blank=True, help_text='Care and maintenance instructions'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_category_path',
            field=models.CharField(blank=True, help_text='Etsy category hierarchy', max_length=500),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_description',
            field=models.TextField(blank=True, help_text='Etsy description (max 102,400 chars)'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_gift_suggestions',
            field=models.TextField(blank=True, help_text='Gift occasion suggestions'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_personalization',
            field=models.TextField(blank=True, help_text='Personalization options available'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_processing_time',
            field=models.CharField(blank=True, help_text='Processing time for orders', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_production_partners',
            field=models.TextField(blank=True, help_text='Production partner information'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_seasonal_keywords',
            field=models.TextField(blank=True, help_text='Seasonal keywords for occasions'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_section_id',
            field=models.CharField(blank=True, help_text='Shop section ID', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_shipping_profile',
            field=models.TextField(blank=True, help_text='Shipping profile information (JSON)'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_size_guide',
            field=models.TextField(blank=True, help_text='Size guide information'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_story_behind',
            field=models.TextField(blank=True, help_text='Story behind the creation'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_style_tags',
            field=models.TextField(blank=True, help_text='Style-specific tags for better discovery'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_sustainability_info',
            field=models.TextField(blank=True, help_text='Sustainability and eco-friendly information'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_target_demographics',
            field=models.TextField(blank=True, help_text='Target buyer demographics'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_title',
            field=models.CharField(blank=True, help_text='Etsy title (max 140 characters)', max_length=140),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_when_made',
            field=models.CharField(blank=True, choices=[('made_to_order', 'Made to order'), ('2020_2024', '2020-2024'), ('2010_2019', '2010-2019'), ('2000_2009', '2000-2009'), ('1990s', '1990s'), ('1980s', '1980s'), ('1970s', '1970s'), ('1960s', '1960s'), ('1950s', '1950s'), ('1940s', '1940s'), ('1930s', '1930s'), ('1920s', '1920s'), ('1910s', '1910s'), ('1900s', '1900s'), ('1800s', '1800s'), ('before_1800', 'Before 1800')], help_text='When was this item made', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_who_made',
            field=models.CharField(blank=True, choices=[('i_did', 'I did'), ('collective', 'A member of my shop'), ('someone_else', 'Another company or person')], help_text='Who made this item', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedlisting',
            name='etsy_materials',
            field=models.TextField(blank=True, help_text='Materials used in creation'),
        ),
        migrations.AlterField(
            model_name='generatedlisting',
            name='etsy_tags',
            field=models.TextField(blank=True, help_text='13 Etsy tags (JSON array, max 20 chars each)'),
        ),
    ]
