# Generated by Django 5.1.3 on 2025-08-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_generatedlisting_etsy_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_value_proposition',
            field=models.TextField(blank=True, help_text='Quality justification and value positioning'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_visual_suggestions',
            field=models.TextField(blank=True, help_text='Photo styling suggestions and visual recommendations'),
        ),
    ]
