# Generated by Django 5.1.3 on 2025-08-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_generatedlisting_etsy_value_proposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_competitor_insights',
            field=models.TextField(blank=True, help_text='Market research and competitor analysis insights'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_customer_service_templates',
            field=models.TextField(blank=True, help_text='Professional email templates for customer communication'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_photography_guide',
            field=models.TextField(blank=True, help_text='Professional photography styling guide with lighting and props'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_policies_templates',
            field=models.TextField(blank=True, help_text='Complete shop policies templates (returns, shipping, privacy)'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_pricing_analysis',
            field=models.TextField(blank=True, help_text='Comprehensive pricing strategy and competitive analysis'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_seasonal_calendar',
            field=models.TextField(blank=True, help_text='12-month marketing and promotional calendar'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_seo_report',
            field=models.TextField(blank=True, help_text='Advanced SEO optimization report and ranking strategies'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_shop_setup_guide',
            field=models.TextField(blank=True, help_text='Complete Etsy shop setup guide with branding, policies, goals'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_social_media_package',
            field=models.TextField(blank=True, help_text='30-day social media content calendar and templates'),
        ),
        migrations.AddField(
            model_name='generatedlisting',
            name='etsy_variations_guide',
            field=models.TextField(blank=True, help_text='Product variations and upselling opportunities guide'),
        ),
    ]
