# Generated by Django 5.1.3 on 2025-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_generatedlisting_etsy_competitor_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_profit_maximizer',
            field=models.TextField(blank=True, help_text='Profit maximization strategies and guidance'),
        ),
    ]
