# Generated by Django 5.1.3 on 2025-08-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_generatedlisting_walmart_profit_maximizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlisting',
            name='walmart_rich_media',
            field=models.TextField(blank=True, help_text='Rich media recommendations JSON'),
        ),
    ]
