# Generated by Django 4.2.16 on 2025-07-23 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('luxury', 'Luxury'), ('playful', 'Playful'), ('minimal', 'Minimal'), ('bold', 'Bold')], max_length=20)),
                ('target_platform', models.CharField(choices=[('amazon', 'Amazon'), ('walmart', 'Walmart'), ('etsy', 'Etsy'), ('tiktok', 'TikTok'), ('shopify', 'Shopify')], max_length=20)),
                ('competitor_urls', models.TextField(help_text='Comma-separated competitor URLs')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categories', models.TextField(help_text='Product categories, comma-separated')),
                ('features', models.TextField(help_text='Key features, comma-separated')),
                ('target_keywords', models.TextField(blank=True, help_text='Target keywords, comma-separated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('key_features', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
