# Generated by Django 4.2.16 on 2025-07-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.TextField(blank=True, default='', help_text='Product categories, comma-separated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='competitor_urls',
            field=models.TextField(blank=True, default='', help_text='Comma-separated competitor URLs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Key features, comma-separated'),
        ),
    ]
