# Generated by Django 4.2.16 on 2025-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_target_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faqs',
            field=models.TextField(blank=True, default='', help_text='Frequently asked questions and answers'),
        ),
        migrations.AddField(
            model_name='product',
            name='long_tail_keywords',
            field=models.TextField(blank=True, default='', help_text='Long-tail keywords for specific searches'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.TextField(blank=True, default='', help_text='Primary SEO keywords for search optimization'),
        ),
        migrations.AddField(
            model_name='product',
            name='whats_in_box',
            field=models.TextField(blank=True, default='', help_text='List of items included in the package'),
        ),
    ]
