# Generated by Django 4.2.16 on 2025-07-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_target_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faqs',
            field=models.TextField(blank=True, default='', help_text='Frequently asked questions'),
        ),
        migrations.AddField(
            model_name='product',
            name='whats_in_box',
            field=models.TextField(blank=True, default='', help_text="What's included in the package"),
        ),
    ]
