# Generated by Django 4.2.16 on 2025-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_faqs_product_long_tail_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='target_keywords',
            field=models.TextField(blank=True, default='', help_text='Target keywords, comma-separated'),
        ),
    ]
