# Generated by Django 4.2.16 on 2025-08-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_target_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, default='', help_text='Amazon Standard Identification Number', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_persona',
            field=models.TextField(blank=True, default='', help_text='Brand personality, values, and voice'),
        ),
        migrations.AddField(
            model_name='product',
            name='competitor_asins',
            field=models.TextField(blank=True, default='', help_text='Comma-separated competitor ASINs'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.CharField(choices=[('us', 'United States'), ('ca', 'Canada'), ('mx', 'Mexico'), ('uk', 'United Kingdom'), ('de', 'Germany'), ('fr', 'France'), ('it', 'Italy'), ('es', 'Spain'), ('nl', 'Netherlands'), ('se', 'Sweden'), ('pl', 'Poland'), ('be', 'Belgium'), ('jp', 'Japan'), ('in', 'India'), ('sg', 'Singapore'), ('ae', 'UAE'), ('sa', 'Saudi Arabia'), ('br', 'Brazil'), ('au', 'Australia'), ('tr', 'Turkey'), ('eg', 'Egypt')], default='us', help_text='Amazon marketplace/country', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace_language',
            field=models.CharField(blank=True, default='en', help_text='Language for the selected marketplace', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience',
            field=models.TextField(blank=True, default='', help_text='Description of ideal customer demographics and psychographics'),
        ),
    ]
