# Generated by Django 5.1.3 on 2025-08-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_asin_product_brand_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, default='', help_text="Special occasion for targeted content (e.g., Christmas, Valentine's Day)", max_length=100),
        ),
    ]
