# Generated by Django 5.1.3 on 2025-08-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Product URL for reference', max_length=500),
        ),
    ]
