# Generated by Django 5.1.3 on 2025-08-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_urls',
            field=models.TextField(blank=True, default='', help_text='Product reference URLs, comma-separated (max 3)'),
        ),
    ]
