# Generated by Django 5.1.3 on 2025-08-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_brand_tone_alter_product_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_tone',
            field=models.CharField(blank=True, choices=[('professional', 'Professional'), ('casual', 'Casual'), ('luxury', 'Luxury'), ('trendy', 'Trendy'), ('playful', 'Playful'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('handmade', 'Handmade'), ('artistic', 'Artistic'), ('vintage', 'Vintage'), ('bohemian', 'Bohemian'), ('minimalist', 'Minimalist'), ('luxury_craft', 'Luxury Craft'), ('eco_friendly', 'Eco-Friendly'), ('whimsical', 'Whimsical'), ('rustic', 'Rustic'), ('modern_craft', 'Modern Craft')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketplace',
            field=models.CharField(choices=[('us', 'United States'), ('ca', 'Canada'), ('mx', 'Mexico'), ('uk', 'United Kingdom'), ('de', 'Germany'), ('fr', 'France'), ('it', 'Italy'), ('es', 'Spain'), ('nl', 'Netherlands'), ('se', 'Sweden'), ('pl', 'Poland'), ('be', 'Belgium'), ('jp', 'Japan'), ('in', 'India'), ('sg', 'Singapore'), ('ae', 'UAE'), ('sa', 'Saudi Arabia'), ('br', 'Brazil'), ('au', 'Australia'), ('tr', 'Turkey'), ('eg', 'Egypt'), ('walmart_usa', 'Walmart USA'), ('walmart_canada', 'Walmart Canada'), ('walmart_mexico', 'Walmart Mexico'), ('etsy_us', 'Etsy USA'), ('etsy_ca', 'Etsy Canada'), ('etsy_uk', 'Etsy UK'), ('etsy_au', 'Etsy Australia'), ('etsy_de', 'Etsy Germany'), ('etsy_fr', 'Etsy France'), ('etsy_it', 'Etsy Italy'), ('etsy_es', 'Etsy Spain'), ('etsy_nl', 'Etsy Netherlands'), ('etsy_be', 'Etsy Belgium'), ('etsy_ie', 'Etsy Ireland'), ('etsy_ch', 'Etsy Switzerland'), ('etsy_at', 'Etsy Austria'), ('etsy_dk', 'Etsy Denmark'), ('etsy_se', 'Etsy Sweden'), ('etsy_no', 'Etsy Norway'), ('etsy_fi', 'Etsy Finland'), ('etsy_pl', 'Etsy Poland'), ('etsy_cz', 'Etsy Czech Republic'), ('etsy_hu', 'Etsy Hungary'), ('etsy_ro', 'Etsy Romania'), ('etsy_bg', 'Etsy Bulgaria'), ('etsy_gr', 'Etsy Greece'), ('etsy_pt', 'Etsy Portugal'), ('etsy_hr', 'Etsy Croatia'), ('etsy_si', 'Etsy Slovenia'), ('etsy_sk', 'Etsy Slovakia'), ('etsy_ee', 'Etsy Estonia'), ('etsy_lv', 'Etsy Latvia'), ('etsy_lt', 'Etsy Lithuania'), ('etsy_mx', 'Etsy Mexico'), ('etsy_br', 'Etsy Brazil'), ('etsy_jp', 'Etsy Japan'), ('etsy_in', 'Etsy India'), ('etsy_sg', 'Etsy Singapore'), ('etsy_hk', 'Etsy Hong Kong'), ('etsy_tw', 'Etsy Taiwan'), ('etsy_kr', 'Etsy South Korea'), ('etsy_nz', 'Etsy New Zealand'), ('etsy_za', 'Etsy South Africa'), ('etsy_il', 'Etsy Israel'), ('etsy_tr', 'Etsy Turkey'), ('etsy_ae', 'Etsy UAE'), ('etsy_sa', 'Etsy Saudi Arabia'), ('etsy_eg', 'Etsy Egypt'), ('etsy_ma', 'Etsy Morocco'), ('etsy_tn', 'Etsy Tunisia'), ('etsy_dz', 'Etsy Algeria'), ('etsy_ng', 'Etsy Nigeria'), ('etsy_ke', 'Etsy Kenya'), ('etsy_gh', 'Etsy Ghana'), ('etsy_ug', 'Etsy Uganda'), ('etsy_tz', 'Etsy Tanzania'), ('etsy_et', 'Etsy Ethiopia'), ('etsy_sn', 'Etsy Senegal'), ('etsy_ci', 'Etsy Ivory Coast'), ('etsy_bw', 'Etsy Botswana'), ('etsy_na', 'Etsy Namibia'), ('etsy_zm', 'Etsy Zambia'), ('etsy_zw', 'Etsy Zimbabwe'), ('etsy_mw', 'Etsy Malawi'), ('etsy_mg', 'Etsy Madagascar'), ('etsy_mu', 'Etsy Mauritius')], default='us', help_text='Marketplace/country for the platform', max_length=15),
        ),
    ]
