# Generated by Django 5.1.3 on 2025-08-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_brand_tone_alter_product_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketplace',
            field=models.CharField(choices=[('us', 'United States'), ('ca', 'Canada'), ('mx', 'Mexico'), ('uk', 'United Kingdom'), ('de', 'Germany'), ('fr', 'France'), ('it', 'Italy'), ('es', 'Spain'), ('nl', 'Netherlands'), ('se', 'Sweden'), ('pl', 'Poland'), ('be', 'Belgium'), ('jp', 'Japan'), ('in', 'India'), ('sg', 'Singapore'), ('ae', 'UAE'), ('sa', 'Saudi Arabia'), ('br', 'Brazil'), ('au', 'Australia'), ('tr', 'Turkey'), ('eg', 'Egypt'), ('walmart_usa', 'Walmart USA'), ('walmart_canada', 'Walmart Canada'), ('walmart_mexico', 'Walmart Mexico'), ('etsy', 'Etsy')], default='us', help_text='Marketplace/country for the platform', max_length=15),
        ),
    ]
