# Generated by Django 5.1.3 on 2025-08-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_tone',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('professional', 'Professional'), ('casual', 'Casual'), ('luxury', 'Luxury'), ('trendy', 'Trendy'), ('playful', 'Playful'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('handmade', 'Handmade'), ('artistic', 'Artistic'), ('vintage', 'Vintage'), ('bohemian', 'Bohemian'), ('minimalist', 'Minimalist'), ('luxury_craft', 'Luxury Craft'), ('eco_friendly', 'Eco-Friendly'), ('whimsical', 'Whimsical'), ('rustic', 'Rustic'), ('modern_craft', 'Modern Craft')], default='', max_length=20),
        ),
    ]
