# Generated by Django 5.1.3 on 2025-08-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_brand_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_tone',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('professional', 'Professional'), ('casual', 'Casual'), ('luxury', 'Luxury'), ('trendy', 'Trendy'), ('playful', 'Playful'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('handmade_artisan', 'Handmade Artisan'), ('vintage_charm', 'Vintage Charm'), ('bohemian_free', 'Bohemian Free-Spirit'), ('cottagecore_cozy', 'Cottagecore Cozy'), ('modern_minimalist', 'Modern Minimalist'), ('whimsical_playful', 'Whimsical & Playful'), ('rustic_farmhouse', 'Rustic Farmhouse'), ('eco_conscious', 'Eco-Conscious'), ('luxury_handcrafted', 'Luxury Handcrafted'), ('artistic_creative', 'Artistic & Creative'), ('messy_coquette', 'Messy Coquette'), ('chateaucore', 'Châteaucore'), ('galactic_metallic', 'Galactic Metallic')], default='', max_length=30),
        ),
    ]
