# Generated by Django 4.2.16 on 2025-08-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_brand_tone_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_tone',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('professional', 'Professional'), ('casual', 'Casual'), ('luxury', 'Luxury'), ('trendy', 'Trendy'), ('playful', 'Playful'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('familiar_caloroso', 'Familiar y Cálido'), ('tradicion_mexicana', 'Tradición Mexicana'), ('lujo_mexicano', 'Lujo Mexicano'), ('joven_vibrante', 'Joven y Vibrante'), ('confiable_profesional', 'Confiable y Profesional'), ('festivo_celebracion', 'Festivo y Celebración'), ('moderno_mexicano', 'Moderno Mexicano'), ('hogareño_familiar', 'Hogareño y Familiar'), ('handmade_artisan', 'Handmade Artisan'), ('vintage_charm', 'Vintage Charm'), ('bohemian_free', 'Bohemian Free-Spirit'), ('cottagecore_cozy', 'Cottagecore Cozy'), ('modern_minimalist', 'Modern Minimalist'), ('whimsical_playful', 'Whimsical & Playful'), ('rustic_farmhouse', 'Rustic Farmhouse'), ('eco_conscious', 'Eco-Conscious'), ('luxury_handcrafted', 'Luxury Handcrafted'), ('artistic_creative', 'Artistic & Creative'), ('messy_coquette', 'Messy Coquette'), ('chateaucore', 'Châteaucore'), ('galactic_metallic', 'Galactic Metallic')], default='', max_length=30),
        ),
    ]
